### PR TITLE
Fix ci errors

### PR DESCRIPTION
**Pull request by HildisviniOttar**
This fixes the clang errors introduced by the previous CI checks.

### CODE REVIEW

**Comment by aquila9r** [comment]
Really sorry to ping, but any chance @bigspider or @lpascal-ledger could review this? We're really eager to get this fixed and would really appreciate the help. Thank you, and apologies again for tagging.

**Review by lpascal-ledger — DISMISSED** [review]
Thanks for the clean-up! I would have merged it immediately, however don't you wish to update the version number (`2.1.1` or `2.2.0`)? The `2.1.0` was deployed on the test provider and tagged 5 months ago.

If you wish for this new version to be deployed, please ask our product team.

**Comment by HildisviniOttar** [comment]
Hi @lpascal-ledger thanks -- bumped to `v2.2.0`. Can you please pass on to product team? They are not appearing to reply on Discord for several weeks.

**Comment by aquila9r** [comment]
Relaying comments

 ```
the security team is requesting that you rebase on the cosmos app becasue many updates from Cosmos are needed in thorchain app:
https://github.com/LedgerHQ/app-thorchain/compare/6c194daa28936e273f9548eabca9e72ba04bb632...2c1a026cba573ac146e3e3bc6a80bd8eef4e3521

Additional comments:

zxlib must be a submodule, else it is too difficult for us to maintain

Dependencies are too old. conanfile.txt is 3 years old

Important problems like https://github.com/LedgerHQ/app-cosmos/commit/814dce8e0d593313a2cd9819fdd154ca68dbc0f7  and https://github.com/LedgerHQ/app-cosmos/commit/403f5b2a7b3a7899679efa3408b2fca4567cd03a, fixed in Cosmos, are not fixed here
```

**Pull request merged**
